version: '3.9'

services:
  express-server:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - '3000:3000'
    container_name: server-express-dev
    links:
      - some-mongo
  some-mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: