version: '3.9'

services:
  express-server:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    ports:
      - '3000:3000'
    container_name: server-express-prod
    links:
      - some-mongo
  express-server-2:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    ports:
      - '4000:3000'
    container_name: server-express-2-prod
    links:
     - some-mongo
  some-mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: